"""initial schema

Revision ID: 344a245f4917
Revises:
Create Date: 2026-07-02 09:28:02.423271

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "344a245f4917"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("household_label", sa.String(length=120), nullable=False),
        sa.Column("c1_first", sa.String(length=80), nullable=False),
        sa.Column("c1_last", sa.String(length=80), nullable=False),
        sa.Column("c1_dob", sa.Date(), nullable=False),
        sa.Column("c1_ssn_last4", sa.String(length=4), nullable=False),
        sa.Column("c1_monthly_salary", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("c2_first", sa.String(length=80), nullable=True),
        sa.Column("c2_last", sa.String(length=80), nullable=True),
        sa.Column("c2_dob", sa.Date(), nullable=True),
        sa.Column("c2_ssn_last4", sa.String(length=4), nullable=True),
        sa.Column("c2_monthly_salary", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("monthly_expense_budget", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "private_reserve_target_override", sa.Numeric(precision=14, scale=2), nullable=True
        ),
        sa.Column("private_reserve_label", sa.String(length=60), nullable=False),
        sa.Column("trust_label", sa.String(length=120), nullable=False),
        sa.Column("trust_property_address", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "c2_ssn_last4 IS NULL OR length(c2_ssn_last4) = 4", name="ck_clients_c2_ssn_4digits"
        ),
        sa.CheckConstraint("length(c1_ssn_last4) = 4", name="ck_clients_c1_ssn_4digits"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column(
            "section",
            sa.Enum(
                "SACS_INFLOW",
                "SACS_OUTFLOW",
                "SACS_PRIVATE_RESERVE",
                "SACS_INVESTMENT",
                "RETIREMENT",
                "NON_RETIREMENT",
                "TRUST",
                name="account_section",
            ),
            nullable=False,
        ),
        sa.Column(
            "owner",
            sa.Enum("CLIENT1", "CLIENT2", "JOINT", "TRUST", name="account_owner"),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "IRA",
                "ROTH_IRA",
                "_401K",
                "PENSION",
                "BROKERAGE",
                "CHECKING",
                "SAVINGS",
                "HYSA",
                "STOCK_OPTIONS",
                "OTHER",
                name="account_kind",
            ),
            nullable=False,
        ),
        sa.Column("custodian", sa.String(length=80), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("last4", sa.String(length=4), nullable=True),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(section != 'RETIREMENT') OR (owner IN ('CLIENT1', 'CLIENT2'))",
            name="ck_accounts_retirement_never_joint",
        ),
        sa.CheckConstraint("last4 IS NULL OR length(last4) = 4", name="ck_accounts_last4_4digits"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_client_id"), ["client_id"], unique=False)
        batch_op.create_index("ix_accounts_client_section", ["client_id", "section"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("entity", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("diff_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_entity", ["entity", "entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_user_id"), ["user_id"], unique=False)

    op.create_table(
        "insurance_deductibles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("insurance_deductibles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_insurance_deductibles_client_id"), ["client_id"], unique=False
        )

    op.create_table(
        "liabilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("MORTGAGE", "AUTO", "HEALTH", "OTHER", name="liability_kind"),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("liabilities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_liabilities_client_id"), ["client_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "FINAL", name="report_status"), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.Column("sacs_pdf_path", sa.String(length=500), nullable=True),
        sa.Column("tcc_pdf_path", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "meeting_date", name="uq_reports_client_meeting"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reports_created_by_user_id"), ["created_by_user_id"], unique=False
        )

    op.create_table(
        "balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "account_id", name="uq_balance_report_account"),
    )
    with op.batch_alter_table("balances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_balances_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_balances_report_id"), ["report_id"], unique=False)

    op.create_table(
        "liability_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("liability_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["liability_id"], ["liabilities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "liability_id", name="uq_liab_balance_report_liab"),
    )
    with op.batch_alter_table("liability_balances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_liability_balances_liability_id"), ["liability_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_liability_balances_report_id"), ["report_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("liability_balances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_liability_balances_report_id"))
        batch_op.drop_index(batch_op.f("ix_liability_balances_liability_id"))

    op.drop_table("liability_balances")
    with op.batch_alter_table("balances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_balances_report_id"))
        batch_op.drop_index(batch_op.f("ix_balances_account_id"))

    op.drop_table("balances")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_created_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_reports_client_id"))

    op.drop_table("reports")
    with op.batch_alter_table("liabilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_liabilities_client_id"))

    op.drop_table("liabilities")
    with op.batch_alter_table("insurance_deductibles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insurance_deductibles_client_id"))

    op.drop_table("insurance_deductibles")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_user_id"))
        batch_op.drop_index("ix_audit_entity")

    op.drop_table("audit_log")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index("ix_accounts_client_section")
        batch_op.drop_index(batch_op.f("ix_accounts_client_id"))

    op.drop_table("accounts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("clients")
    # ### end Alembic commands ###
